// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3ibu59IYbak_mJ9OQHad56V5JmUFxwWQ',
    appId: '1:679925068848:web:8c28faf8954fb3e51f29f5',
    messagingSenderId: '679925068848',
    projectId: 'fir-masterclass-cb3ff',
    authDomain: 'fir-masterclass-cb3ff.firebaseapp.com',
    storageBucket: 'fir-masterclass-cb3ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFOsdcF91O-5gTOzOBLedNxrvNIWYecFE',
    appId: '1:679925068848:android:f61c804bd348fcd41f29f5',
    messagingSenderId: '679925068848',
    projectId: 'fir-masterclass-cb3ff',
    storageBucket: 'fir-masterclass-cb3ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb1QzuA78U3KhKvrq82KyUffMGTN4Jidw',
    appId: '1:679925068848:ios:420e78945d589d2a1f29f5',
    messagingSenderId: '679925068848',
    projectId: 'fir-masterclass-cb3ff',
    storageBucket: 'fir-masterclass-cb3ff.appspot.com',
    iosClientId: '679925068848-8qg5ericju62org5qfis2hclsd90itpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseMasterClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb1QzuA78U3KhKvrq82KyUffMGTN4Jidw',
    appId: '1:679925068848:ios:420e78945d589d2a1f29f5',
    messagingSenderId: '679925068848',
    projectId: 'fir-masterclass-cb3ff',
    storageBucket: 'fir-masterclass-cb3ff.appspot.com',
    iosClientId: '679925068848-8qg5ericju62org5qfis2hclsd90itpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseMasterClass',
  );
}
